### ISSUE TITLE
Return IActionResult from Notes API endpoints

### ISSUE THREAD

**Issue by bfren** [strasnote/strasnote#179]
We need to return `IActionResult` so error responses can be returned gracefully.

**Comment by bencgreen** [comment]
@cwn-dev so there is something to discuss here - to do this the `Is.AuthenticatedUser` function needs to return `IActionResult`, so the code that returns a value / Not Authorised / Not Found / Error is shared.

However at present this is in Strasnote.Util, and works off `IAppContext` which is agnostic about the hosting platform - yet `IActionResult` is in an ASP.NET namespace.

The question is, do we have a web-specific function in the Util namespace (which is supposed to be totally generic)?

**Comment by bencgreen** [comment]
We could, for example, make our own abstract ApiController, which has a `Process` method (or something) to handle all this?  The advantage then is that it has access to the standard `NotFound()` etc methods.

**Comment by bencgreen** [comment]
Something like this:

```csharp
public abstract class Controller : Microsoft.AspNetCore.Mvc.Controller
{
	protected IAppContext Context { get; private init; }

	protected ILog Log { get; private init; }

	protected Controller(IAppContext context, ILog log) =>
		(Context, Log) = (context, log);

	protected Task<IActionResult> ProcessAsync<T>(Func<long, Task<T>> then, Func<IActionResult>? otherwise = null)
	{
		return Is.AuthenticatedUser<IActionResult>(
			ctx: Context,

			//
			// Runs if the request has a valid authenticated user
			//

			then: async userId =>
			{
				try
				{
					// Execute function
					var result = await then(userId).ConfigureAwait(false);

					// Process the result
					return result switch
					{
						T value =>
							Json(value),

						_ =>
							NotFound()
					};
				}
				catch (Exception ex)
				{
					// Log any errors that occurred while function was being executed
					Log.Error(ex, "Error processing controller function.");
					return StatusCode(500);
				}
			},

			//
			// Runs if the request is not authorised
			//

			otherwise: () =>
			{
				// Return unauthorised by default
				if (otherwise is null)
				{
					return Unauthorized();
				}

				try
				{
					// Execute function
					return otherwise();
				}
				catch (Exception ex)
				{
					// Log any errors that occurred while function was being executed
					Log.Error(ex, "Error processing unauthorised function.");
					return StatusCode(500);
				}
			}
		);
	}
}
```

**Comment by bencgreen** [comment]
The idea is that if the `then` function returns null, that means 'Not Found'.

**Comment by bencgreen** [comment]
That then enables this in the Controller:

```csharp
[HttpPost]
public Task<IActionResult> Create() =>
	ProcessAsync(
		userId => notes.CreateAsync(new()
		{
			UserId = userId
		})
	);
```

**Comment by bencgreen** [comment]
The disadvantage of this that I can see is from a Swagger / API point of view - it now doesn't say anything about what is returned / promised.

**Comment by bencgreen** [comment]
I've pushed some code to a branch for all this for you to look at
