### ISSUE TITLE
Ensure MySQL connection pooling is working

### ISSUE THREAD

**Issue by cwn-dev** [strasnote/strasnote#208]
I don't think pooling will work currently as we do ```new MySqlConnection(ConnectionString)``` in ```MySqlClient.cs```

We should use ```MySqlConnection.Open``` which retrieves a connection from the pool.

See here: https://mysqlconnector.net/connection-options/#connection-pooling-options
And here: https://dev.mysql.com/doc/connector-net/en/connector-net-connections-pooling.html

> One approach that simplifies things is to avoid creating a MySqlConnection object manually. Instead, use the overloaded methods that take a connection string as an argument. With this approach, Connector/NET automatically creates, opens, closes and destructs connections, using the connection pooling system for best performance.

**Comment by bfren** [comment]
OpenAsync would be good to use so everything is fully async.

**Comment by bfren** [comment]
So with this, the docs say:

> Enables connection pooling. When pooling is enabled, MySqlConnection.Open/OpenAsync retrieves an open connection from the pool if one is available.

Those functions are what's used by Dapper's query functions so pooling is used.  However, I suggest we use OpenAsync to ensure it's opened in an async way.
