### ISSUE TITLE
Make sure all DateTimes are UTC

### ISSUE THREAD

**Issue by cwn-dev** [strasnote/strasnote#213]
We should use DateTimeOffset or might be better to use DateTimeUtc. Either way, we shouldn't be using DateTime.

**Comment by bfren** [comment]
I'm wondering if we should use [NodaTime](https://nodatime.org/) instead?

**Comment by bfren** [comment]
This is best done with a custom Dapper TypeHandler - db backends don't play nice with DateTimeUtc and DateTimeOffset e.g. [here](https://dapper-tutorial.net/knowledge-base/12510299/get-datetime-as-utc-with-dapper)
