### ISSUE TITLE
Use implicit usings for test projects

### ISSUE THREAD

**Issue by bfren** [strasnote/strasnote#231]
It's super useful for test projects, though you have to watch NuGet updates as unless you update them in Directory.Build.props, individual references will be added to each project.

I suggest the following common packages:

* Microsoft.NET.Test.Sdk
* NSubstitute
* Xunit
* (Project reference to Strasnote.Util)

And the following as implicit usings:

* NSubstitute
* Rnd
* Strasnote.Util

**Comment by cwn-dev** [comment]
Sounds good to me
