### ISSUE TITLE
Use secrets in ConfigureServices() instead of hard coding signing key

### ISSUE THREAD

**Issue by bencgreen** [strasnote/strasnote#57]

**Comment by bencgreen** [comment]
This is done in Encryption branch, it will be merged when that is finished.

**Comment by cwn-dev** [comment]
Isn't this effectively still calling IConfiguration from Startup.cs?
Although I guess as it's using IConfiguration itself it should be ok, I would assume!

**Comment by bencgreen** [comment]
No, because it's in a lambda function - it's called later, after Services is configured.  I've tested it and it works like a charm - even *before* AuthConfig is registered... which proves it's not run at the time.

**Comment by cwn-dev** [comment]
Awesome! Good find! 😁
