### ISSUE TITLE
Logging in with non-existent user throws exception

### ISSUE THREAD

**Issue by cwn-dev** [strasnote/strasnote#83]
This is because RetrieveByEmail is returning TModel instead of TModel?

**Comment by bencgreen** [comment]
Yes I think so - I will start going through and adding nullability to the return type.

**Comment by bencgreen** [comment]
OK so it's a little more complicated than that.  `FindByNameAsync()` and `FindByEmailAsync()` are both required methods on `IUserStore` and cannot return nullable types.

So either we leave it and handle the exceptions elsewhere, or throw an exception at that point if the repository method returns a null object.

**Comment by bencgreen** [comment]
And to be honest if we're doing that we should probably make all the methods that return a single item nullable, because we can't promise we'll be returning an object every time - as we discussed regarding the nullability of `RetrieveAsync` on `SqlRepository`.

**Comment by cwn-dev** [comment]
Yup sounds good - we can make all single item returns nullable & just throw an exception in UserStore. It should never hit that exception unless somebody is trying something strange

**Comment by bencgreen** [comment]
Yup, I'm on it - that's what I thought so I got on with it pending your approval!  Will push what I'm doing in a mo.
